apiVersion: v1
kind: Service
metadata:
  name: cluster-imager-api
  namespace: default
  labels:
    app: cluster-imager
    component: api
spec:
  selector:
    app: cluster-imager
    component: api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
